aplicaciones/encargados/urls.py
#Urls de la aplicacion docente
from django.conf.urls import url,include
from django.contrib.auth.decorators import login_required
from aplicaciones.encargados.views import index_encargados,EncargadoListView,EncargadoCreateView
urlpatterns = [
    url(r'^index$', login_required(index_encargados) , name='index_encargados'),# el signo $ indica que es una exprecion regular, cadena vacia junto con el signo ^.
    url(r'^listado$', login_required(EncargadoListView.as_view()) , name='listado'),# el signo $ indica que es una exprecion regular, cadena vacia junto con el signo ^.
    url(r'^nuevo$', login_required(EncargadoCreateView.as_view()) , name='nuevo'),# el signo $ indica que es una exprecion regular, cadena vacia junto con el signo ^.
    

]

registro_inscripcion/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from registro_inscripcion.views import GeneratePdf
from django.contrib.auth.views import login,logout_then_login, password_reset,password_reset_done,password_reset_confirm,password_reset_complete


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^alumnos/', include('aplicaciones.alumnos.urls',namespace="alumnos")),#vista principal de la aplicacion alumnos
    url(r'^docentes/', include('aplicaciones.docentes.urls',namespace="docentes")),#vista principal de la aplicacion alumnos
    # el namespace lo utilizaremos en las templates para llamar una url de manera mas convencional
    url(r'^encargados/', include('aplicaciones.encargados.urls',namespace="encargados")),
    url(r'^usuarios/', include('aplicaciones.usuarios.urls',namespace="usuarios")),
    url(r'^accounts/login/',login,{'template_name':'login.html'}, name='login'),
    url(r'^logout/',logout_then_login,name='logout'),#vista para deslogear usuario
    url(r'^reset/password_reset',password_reset,{'template_name':'password_reset_form.html','email_template_name':'password_reset_email.html'},name='password_reset'),
    url(r'^reset/password_reset_done',password_reset_done,{'template_name':'password_reset_done.html'},name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',password_reset_confirm,{'template_name':'password_reset_confirm.html'},name='password_reset_confirm'),
    url(r'^reset/done',password_reset_complete,{'template_name':'password_reset_complete.html'},name='password_reset_complete'),
    url(r'^pdf/',GeneratePdf.as_view()),
]

aplicaciones/encargados/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from django.utils import *
from django.db import models
from aplicaciones.alumnos.models import Alumno



class Encargado(models.Model):

    #DATOS ENCARGADO
    dui = models.CharField(blank=True, max_length=100,help_text="Ingrese numero de DUI sin guiones")
    alumno = models.OneToOneField(Alumno,null=True, blank=True)#alumno que tiene este encargado
    nombre_encargado =  models.CharField(null= True, blank= True,max_length=60,help_text="Ingrese un nombre valido")
    apellido_encargado = models.CharField(blank=False, max_length=60)
    fecha_nacimiento_encargado = models.DateField(blank=True, null=True)



#Datos PADRES DEL Alumno


    nombre_madre = models.CharField(null= True, blank= True,max_length=60)
    dui_madre = models.CharField(null= True, blank= True,max_length=60)
    ocupacion_madre = models.CharField(null= True, blank= True,max_length=60)
    nombre_padre = models.CharField(null=True,blank=True,max_length=60)
    dui_padre = models.CharField(null= True, blank= True,max_length=60)
    ocupacion_padre = models.CharField(null= True, blank= True,max_length=60)
    def __unicode__(self):
		return '{}'.format(self.nombre_encargado  )

aplicaciones/encargados/forms.py
from django import forms
from aplicaciones.encargados.models import Encargado


class Encargado_Form(forms.ModelForm):
    class Meta:
        model=Encargado

        fields = [
            'nombre_encargado',
            'apellido_encargado',
            'dui',
            'fecha_nacimiento_encargado',
            'nombre_madre',
            'dui_madre',
            'ocupacion_madre',
            'nombre_padre',
            'dui_padre',
            'ocupacion_padre',

        ]
        labels = {
            'nombre_encargado'  :'Nombre Encargado',
            'apellido_encargado' :'Apellido',
            'dui': 'DUI',
            'fecha_nacimiento_encargado' :'Fecha de Nacimiento de Encargado',

        }
        widgets = {
            'nombre_encargado' : forms.TextInput(attrs={'class':'form-control'}),
            'apellido_encargado':forms.TextInput(attrs={'class':'form-control'}),
            'dui':forms.TextInput(attrs={'class':'form-control'}),
            'fecha_nacimiento_encargado':forms.TextInput(attrs={'class':'form-control'}),
            'nombre_madre':forms.TextInput(attrs={'class':'form-control'}),
            'dui_madre':forms.TextInput(attrs={'class':'form-control'}),
            'ocupacion_madre':forms.TextInput(attrs={'class':'form-control'}),
            'nombre_padre':forms.TextInput(attrs={'class':'form-control'}),
            'dui_padre':forms.TextInput(attrs={'class':'form-control'}),
            'ocupacion_padre':forms.TextInput(attrs={'class':'form-control'}),

        }

aplicaciones/encargados/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse,HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render,redirect
from django.views.generic import ListView, CreateView
from aplicaciones.alumnos.models import Alumno
from aplicaciones.encargados.models import Encargado
from aplicaciones.alumnos.forms import Alumno_Form
from aplicaciones.encargados.forms import Encargado_Form
# Create your views here.
def index_encargados(request):
    return render(request,'index_principal_encargados.html')


class EncargadoListView(ListView):

    model = Encargado
    template_name = 'listado_encargados.html'
class EncargadoCreateView(CreateView):
    model = Encargado
    form_class = Encargado_Form
    second_form_class = Alumno_Form
    template_name = 'CRUD_encargados.html'
    success_url =reverse_lazy('encargados:listado')

    def get_context_data(self, **kwargs):
        context =super(EncargadoCreateView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form']  = self.form_class(self.request.GET)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(self.request.GET)
        return  context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        form2 = self.second_form_class(request.POST)
        if form.is_valid() and form2.is_valid():
            encargado = form.save(commit=False)
            encargado.alumno = form2.save()
            encargado.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form, form2=form2))

aplicaciones/encargados/templates/CRUD_encargados.html
{%extends 'index_principal_encargados.html' %} {% block extraheader %} {% endblock %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-5">
      <div class="panel panel-primary ">
        <div class="panel-heading">
          <h3 class="panel-title"><i class=""></i><center>Datos encargado</center></h3>
        </div>
      </div>
      <div class="formularios">
        <form method="post">
          {% csrf_token %}
          <br>
          <div class="input-group">
            <span class="input-group-addon">Nombre del Encargado:</span>
            <input value="{{encargado.nombre_encargado}}" type="text" class="form-control" name="nombre_encargado" placeholder="Nombre de encargado">
          </div>
          <br>
          <div class="input-group">
            <span class="input-group-addon">Apellido del encargado:</span>
            <input value="{{encargado.apellido_encargado}}" type="text" class="form-control" name="apellido_encargado" placeholder="Apellido de encargado">
          </div>
          <br>
          <div class="input-group">
            <span class="input-group-addon">DUI del encargado:</span>
            <input value="{{encargado.dui}}" type="text" class="form-control" name="dui" placeholder="dui de encargado">
          </div>
          <br>
          <div class='input-group '>
            <span class="input-group-addon validity ">Fechas/Nac/Encargado || <i class="glyphicon glyphicon-calendar"></i></span>

            <input value="{{encargado.fecha_nacimiento_encargado}}" class="form-control" type="date" id="party" name="fecha_nacimiento_encargado" >
          </div>
          <br>
          <div class="panel panel-primary ">
            <div class="panel-heading">
              <h3 class="panel-title"><i class=""></i><center>Datos Madre</center></h3>
            </div>
          </div>
          {# DATOS DE LA MADRE #}
          <div class="input-group">
            <span class="input-group-addon">Nombre de la madre:</span>
            <input value="{{encargado.nombre_madre}}" type="text" class="form-control" name="nombre_madre" placeholder="Nombre de la madre">
          </div>
          <br>
          <br>
          <div class="input-group">
            <span class="input-group-addon">Dui de la madre:</span>
            <input value="{{encargado.dui_madre}}" type="text" class="form-control" name="dui_madre" placeholder="Numero de Dui sin guiones">
          </div>
          <br>
          <br>
          <div class="input-group">
            <span class="input-group-addon">Ocupacion de la madre:</span>
            <input value="{{encargado.ocupacion_madre}}" type="text" class="form-control" name="ocupacion_madre" placeholder="Ocupacion">
          </div>
          <br>
          <div class="panel panel-primary ">
            <div class="panel-heading">
              <h3 class="panel-title"><i class=""></i><center>Datos Padre</center></h3>
            </div>
          </div>
          {# DATOS DEL PADRE #}

          <div class="input-group">
            <span class="input-group-addon">Nombre del padre:</span>
            <input value="{{encargado.nombre_padre}}" type="text" class="form-control" name="nombre_padre" placeholder="Nombre del padre">
          </div>
          <br>
          <br>
          <div class="input-group">
            <span class="input-group-addon">Dui del padre:</span>
            <input value="{{encargado.dui_padre}}" type="text" class="form-control" name="dui_padre" placeholder="Numero de Dui sin guiones">
          </div>
          <br>
          <br>
          <div class="input-group">
            <span class="input-group-addon">Ocupacion del padre:</span>
            <input value="{{encargado.ocupacion_padre}}" type="text" class="form-control" name="ocupacion_padre" placeholder="Ocupacion">
          </div>
          <br>

      </div>
    </div>
    {# DATOD DEL ALUMNO #}
    <div class="col-md-5">
      <div class="panel panel-primary ">
        <div class="panel-heading">
          <h3 class="panel-title"><i class=""></i><center>Datos de alumnno</center></h3>
        </div>
      </div>
      <div class="formularios">
        <br>
        <div class="input-group">
          <span class="input-group-addon">Nombre de Alumno:</span>
          <input value="{{alumno.nombre}}" type="text" class="form-control" name="nombre" placeholder="Nombre de alumno">
        </div>
        <br>
        <div class="input-group">
          <span class="input-group-addon">Apellido de Alumno:</span>
          <input value="{{alumno.apellido}}" type="text" class="form-control" name="apellido" placeholder="Apellido de alumno">
        </div>
        <br>
        <div class='input-group '>
          <span class="input-group-addon validity ">Fechas/Nacimiento || <i class="glyphicon glyphicon-calendar"></i></span>

          <input value="{{alumno.fecha_nacimiento}}" class="form-control" type="date" id="party" name="fecha_nacimiento" min="2010-04-01" max="2015-04-20" required>
        </div>
        <br>
        <div class="input-group">
          <span class="input-group-addon">Docente a Cargo</span>
          <option value="{{docente_encargado.id}}">{{form2.docente_encargado}} </option>
        </div>

        <br>
        <div class="input-group">
          <span class="input-group-addon">Direccion del alumno</span>
          <input value="{{alumno.direccion_actual}}" type="text" class="form-control" name="direccion_actual" placeholder="Direccion del infante">
        </div>
        <br>
        <br>
        <div class="input-group">
          <span class="input-group-addon">Telefono de casa</span>
          <input value="{{alumno.telefono_actual_casa}}" type="text" class="form-control" name="telefono_actual_casa" placeholder="Celular o fijo">
        </div>
        <br>

        <br>
        <div class="input-group">
          <span class="input-group-addon">Ultimo Centro de estudios</span>
          <input value="{{alumno.ultimo_centro_de_estudio}}" type="text" class="form-control" name="ultimo_centro_de_estudio" placeholder="Ingrese el lugar anterior">
        </div>
        <br>
        <div class="input-group">
          <span class="input-group-addon">Comentarios <br><br>importantes</span>
          <textarea class="form-control" type="text" name="comentarios" value="{{alumno.comentarios}}" rows="4" cols="8"></textarea>
        </div>
        </div>

        <button type="submit">Guardar Registro</button>
        </form>

    </div>
  </div>
</div>
<br><br> {% endblock %}

aplicaciones/encargados/templates/index_principal_encargados.html
 {%extends 'base/base.html' %}
 {% load staticfiles %}
  {% block side_bar %}

<div class="container col-md-2 ">

  <div class="tabbable tabs-left ">

    <ul class="nav nav-tabs">

        <a href=""class="list-group-item active"><h5> Encargados</h5></a>
      <li class="nav-tabs"></li>
      <li><a href="{% url 'encargados:nuevo'%}" data-toggle="tab">Nuevo Registro</a></li>
      <li><a href="{% url 'encargados:listado'%}" data-toggle="tab">Lista de padres y encargados</a></li>
      <li><a href="#" data-toggle="tab">Ver por grados</a></li>
      <li><a href="#" data-toggle="tab">Reportes</a></li>
    </ul>
  </div>

</div>

{% endblock side_bar %} {% block content %}
<div class="bs-calltoaction bs-calltoaction-primary">
  <div class="row">
    <div class="col-md-8 cta-contents">
      <img src="{% static "img/mined.png" %}" width="75" height="75" alt="My image"/>

      <h1 class="text-info">Datos de Persona Encargada:</h1>
      <div class="cta-desc">
        <li class="text-warning">
          DUI
        </li>
        <li class="text-warning">
          NIT
        </li>
        <li class="text-warning">
          TELEFONO
        </li>
        <br>
      </div>
    </div>
    <div class="col-md-3 cta-button">
      <a href="#" class="btn btn-lg btn-block btn-primary">Descarga formulario de encargados</a>
    </div>
  </div>
</div>
  {% endblock content %}

aplicaciones/encargados/templates/listado_encargados.html
 {%extends 'index_principal_encargados.html' %}
 {% load staticfiles %}
 {% block extraheader %}
 <link rel="stylesheet" href="{% static 'css/datatables.min.css '%}">
 {% endblock extraheader %}
  {% block content %}
<div class="container-fluid col-sm-9">
  <div class="row-fluid">
    <div class="table-responsive ">
      <div class="panel panel-primary ">
        <div class="panel-heading">
          <h3 class="panel-title"><i class=""></i><center>Listado de Encargados/padres</center></h3>
        </div>
      </div>
      <table class="table   table-striped table-bordered table-hover table-condensed table-responsive" table id="Jtabla" class="display" cellspacing="0" width="100%">
        <thead>
          <tr class="success" >
            <th>Codigo del Encargado</th>
            <th>NOMBRE Padre o Encargado</th>
            <th>APELLIDO Padre o Encargado</th>
            <th>NUMERO DE DUI</th>
            <th>CODIGO ALUMNO</th>
            <th>Alumno bajo cargo</th>
        </thead>
        <tbody>
          <tr>
            {% if object_list %} {% for encargado in object_list%}
            <td>{{encargado.id}}</td>
            <td> {{encargado.nombre_encargado}}</td>
            <td> {{encargado.apellido_encargado}}</td>
            <td>{{encargado.dui}}</td>
            <td>{{encargado.alumno.id}}</td>
            <td>  {{encargado.alumno.nombre}}</td>
        </tr>
          {%endfor%}
          {%else%}
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <h3><strong>No hay registros de encados</strong></h3>
          </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
  </div>
</div>
<!-- <script src="{% static 'TableFilter/tablefilter.js'%}"></script> -->
 <script src="{% static 'js/filtro_Jtabla_Id.js'%}"></script>
 <!-- <script src="{% static 'js/fecha.js'%}"></script> -->
 <!--llamando el archivo de fitro DataTables-->
{% endblock %}