aplicaciones/alumnos/urls.py
#Urls de la aplicacion Alumno
from django.conf.urls import url,include
from django.contrib.auth.decorators import login_required
from aplicaciones.alumnos.views import index_alumnos,AlumnoListView,AlumnoCreateView,\
AlumnoUpdateView,AlumnoDeleteView,AlumnoDetailView
#barra invertida para salto de linea
urlpatterns = [
    url(r'^index$', login_required(index_alumnos), name='index_alumnos'),# el signo $ indica que es una exprecion regular, cadena vacia junto con el signo ^.
    url(r'^nuevo$', login_required(AlumnoCreateView.as_view()), name='nuevo'),
    url(r'^listado$', login_required(AlumnoListView.as_view()), name='listado'),#pasando la clases
    url(r'^detalles/(?P<pk>\d+)/$', login_required(AlumnoDetailView.as_view()), name='detalles'),
    #de la vista generica como vista, tambiense se puede colocar un contexto de NOMBRE
    #desde la clase con context_object_name
    url(r'^editar/(?P<pk>\d+)/$', login_required(AlumnoUpdateView.as_view()), name='editar'),# para acceder
    #a cada id de los objetos con las  vstas genericas es necesario usar
    # el parametro pk (primary key)
    url(r'^borrar/(?P<pk>\d+)/$', login_required(AlumnoDeleteView.as_view()), name='borrar'),

]

registro_inscripcion/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from registro_inscripcion.views import GeneratePdf
from django.contrib.auth.views import login,logout_then_login, password_reset,password_reset_done,password_reset_confirm,password_reset_complete


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^alumnos/', include('aplicaciones.alumnos.urls',namespace="alumnos")),#vista principal de la aplicacion alumnos
    url(r'^docentes/', include('aplicaciones.docentes.urls',namespace="docentes")),#vista principal de la aplicacion alumnos
    # el namespace lo utilizaremos en las templates para llamar una url de manera mas convencional
    url(r'^encargados/', include('aplicaciones.encargados.urls',namespace="encargados")),
    url(r'^usuarios/', include('aplicaciones.usuarios.urls',namespace="usuarios")),
    url(r'^accounts/login/',login,{'template_name':'login.html'}, name='login'),
    url(r'^logout/',logout_then_login,name='logout'),#vista para deslogear usuario
    url(r'^reset/password_reset',password_reset,{'template_name':'password_reset_form.html','email_template_name':'password_reset_email.html'},name='password_reset'),
    url(r'^reset/password_reset_done',password_reset_done,{'template_name':'password_reset_done.html'},name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',password_reset_confirm,{'template_name':'password_reset_confirm.html'},name='password_reset_confirm'),
    url(r'^reset/done',password_reset_complete,{'template_name':'password_reset_complete.html'},name='password_reset_complete'),
    url(r'^pdf/',GeneratePdf.as_view()),
]

aplicaciones/alumnos/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from django.utils import *
from django.db import models
from datetime import datetime

#importar el modelo docente para hacer la relacion de uno a muchos en este modelo
#  que apunte al de los docentes
from aplicaciones.docentes.models import Docente


class AutoDateTimeField(models.DateTimeField):
    def pre_save(self, model_instance, add):
        return datetime.datetime.now()
# Create your models here.
class Alumno(models.Model):#todo nombre de modelo debe ser un nombre en singular
    #creando los campos del modelo

    nombre = models.CharField(blank=False, max_length=60)
    apellido = models.CharField(blank=False, max_length=60)
    fecha_nacimiento = models.DateField(blank=True, null=True)
    fecha_inscripcion = models.DateField(default=timezone.now)
    docente_encargado =  models.ForeignKey(Docente, null= True, blank= True)
    direccion_actual = models.CharField(blank=True, max_length=60,null=True)
    telefono_actual_casa = models.CharField(blank=False, max_length=60, null=True)
    ultimo_centro_de_estudio=models.CharField(blank=False, max_length=60,null=True)
    comentarios = models.CharField(blank=False, max_length=100,null=True)
    def __unicode__(self):#funcion para que se nos devuelva el nombre y no el objeto
	#que hemos registrado
		return '{}'.format(self.nombre)
    # def` get_full(self):
        #hacer consulta de cuantos registros hay con querysetfilter count y validar for
        #mularios con js
        #
        #
        #
        #

aplicaciones/alumnos/forms.py
# -*- coding: utf-8 -*-
from django import forms
from aplicaciones.alumnos.models import Alumno# importando modelo alumno


class Alumno_Form(forms.ModelForm):
    class Meta:
        model=Alumno

        fields = [

            'nombre',
            'apellido',
            'fecha_nacimiento',
            'docente_encargado',
            'direccion_actual',
            'telefono_actual_casa',
            'ultimo_centro_de_estudio',
            'comentarios',

        ]
        labels = {
            'nombre'  :'Nombres del niño/a:',
            'apellido' :'Apellidos del niño/a',
            'fecha_nacimiento' :'Fecha de Nacimiento',
            'docente_encargado': ' Maestro encargado',
            'comentarios':'Comentarios'

        }
        widgets = {
            'nombre' : forms.TextInput(attrs={'class':'form-control'}),
            'apellido':forms.TextInput(attrs={'class':'form-control'}),
            'fecha_nacimiento':forms.TextInput(attrs={'class':'form-control'}),
            'docente_encargado': forms.Select(attrs={'class':'form-control'}),
            'telefono_actual_casa':forms.TextInput(attrs={'class':'form-control'}),
            'direccion_actual':forms.TextInput(attrs={'class':'form-control'}),
            'ultimo_centro_de_estudio':forms.TextInput(attrs={'class':'form-control'}),
            'Comentarios': forms.Textarea(attrs={'cols': 8, 'rows': 8}),


        }

aplicaciones/alumnos/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.views.generic import ListView,CreateView,UpdateView,DeleteView,DetailView#importando la clase
#listviewView
from django.core.urlresolvers import reverse_lazy
from aplicaciones.alumnos.forms import Alumno_Form
from aplicaciones.alumnos.models import Alumno

#vista principal alumnos
def index_alumnos(request):
    return render(request,'index_principal.html')


#VISTA CREAR BASADA EN CLASES
class AlumnoListView(ListView):#vista basada en clases
    model = Alumno
    queryset = Alumno.objects.all()#ordenando

    template_name = 'listado_alumnos.html'

class AlumnoDetailView(DetailView):
    model = Alumno
    queryset = Alumno.objects.all()#ordenando
    template_name = 'detalles_alumnos.html'



class AlumnoCreateView(CreateView):#vista basada en clases
    model = Alumno#indicando el nombre del modelo a usar
    form_class = Alumno_Form#atributo form class se usa
    # para guardar el formulario que hemos creado
    template_name = 'CRUD_alumnos.html'#se coloca el templateview
    #que se va a utilizar
    success_url = reverse_lazy('alumnos:index_alumnos')#indicando la url
    #a la que volvera luego de guardado el objeto
    #
    #
    #VISTA PARA EDITAR LOS OBJETOS ALUMNOS
class AlumnoUpdateView(UpdateView):
    model = Alumno#indicando el nombre del modelo a usar
    form_class = Alumno_Form#atributo form class se usa
    # para guardar el formulario que hemos creado
    template_name = 'CRUD_alumnos.html'#se coloca el templateview
    #que se va a utilizar
    success_url = reverse_lazy('alumnos:index_alumnos')#indicando la url
    #a la que volvera luego de guardado el objeto
    @method_decorator(permission_required('alumnos.changue_alumno',reverse_lazy('alumnos:listado')))
    def dispatch(self, *args, **kwargs):
            return super(AlumnoUpdateView, self).dispatch(*args, **kwargs)
class AlumnoDeleteView(DeleteView):
    model = Alumno
    template_name = 'eliminar_alumnos.html'
    success_url =reverse_lazy('alumnos:listado')

aplicaciones/alumnos/templates/CRUD_alumnos.html
{%extends 'index_principal.html' %} {% load staticfiles%}
{% block extraheader %}

 {% endblock %}
 {% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-offset-1 col-md-4">
      <div class="panel panel-primary ">
        <div class="panel-heading">
          <h3 class="panel-title"><i class=""></i><center>Registro de los  alumnnos</center></h3>
        </div>
      </div>
      <div class="formularios">

        <form method="post">
          {% csrf_token %}

          <br>
          <div class="input-group">
            <span class="input-group-addon">Nombre de Alumno:</span>
            <input value="{{alumno.nombre}}" type="text" class="form-control" name="nombre" placeholder="Nombre de alumno">
          </div>
          <br>
          <div class="input-group">
            <span class="input-group-addon">Apellido de Alumno:</span>
            <input value="{{alumno.apellido}}" type="textarea" class="form-control" name="apellido" placeholder="Apellido de alumno">
          </div>

          <br>

      <div class='input-group '>

            <span class="input-group-addon validity">Fechas/Nacimiento || <i class="glyphicon glyphicon-calendar"></i></span>

            <input value="{{alumno.fecha_nacimiento}}" class="form-control" type="date" id="" name="fecha_nacimiento" min="2010-04-01" max="2015-04-20" required>

      </div>
      <br>
      <div class="input-group">

        <span class="input-group-addon">Docente a Cargo</span>
        <option value="{{docente_encargado.id}}">{{form.docente_encargado}} </option>

      </div>
      <br>

      <div class="input-group">
        <span class="input-group-addon">Direccion actual </span>
        <input value="{{alumno.direccion_actual}}" type="text" class="form-control" name="direccion_actual" placeholder="Direccion donde vive">

      </div>
      <br>

      <div class="input-group">
        <span class="input-group-addon">Telefono casa</span>
        <input value="{{alumno.telefono_actual_casa}}" type="text" class="form-control" name="telefono_actual_casa" placeholder="Telefono casa">

      </div>
      <br>

      <div class="input-group">
        <span class="input-group-addon">Ultimo Centro de estudios</span>
        <input value="{{alumno.ultimo_centro_de_estudio}}" type="text" class="form-control" name="ultimo_centro_de_estudio" placeholder="Ingrese el lugar anterior">

      </div>
      <br>
      <div class="input-group">
        <span class="input-group-addon">Comentarios <br><br>importantes</span>
        <textarea  value="{{alumno.comentarios}}" class="form-control" type="text" name="comentarios"  rows="6" cols="15"></textarea>
      </div>
      <br>
      <button type="submit">Guardar</button>
      </form>
    </div>
  </div>
</div>
</div>


{% endblock %}

aplicaciones/alumnos/templates/detalles_alumnos.html
{%extends 'index_principal.html' %} {% load staticfiles %} {% block extraheader %}


{% endblock extraheader %} {% block content %}
     <form method="post">
       {% csrf_token %}

       <div class="col-md-5">
         <div class="panel panel-primary ">
           <div class="panel-heading">
             <h3 class="panel-title"><i class=""></i><center><strong>Nombre: </strong>{{alumno.nombre}} {{alumno.apellido}} <strong>ID: </strong>{{alumno.id}}</center></h3>
           </div>
         </div>
         <div class="formularios">
           <br>
           <div class="input-group">
             <span class="input-group-addon"><strong> Nombre de Alumno</strong> </span>
             <input value="{{alumno.nombre}}" type="text" class="form-control" name="nombre" placeholder="Nombre de alumno"  disabled>
           </div>
           <br>
           <div class="input-group">
             <span class="input-group-addon"><strong>Apellido de Alumno</strong> </span>
             <input value="{{alumno.apellido}}" type="text" class="form-control" name="apellido" placeholder="Apellido de alumno" disabled>
           </div>
           <br>
           <div class='input-group '>
             <span class="input-group-addon validity "><strong>Fechas/Nacimiento |</strong>  <i class="glyphicon glyphicon-calendar"></i></span>

             <input value="{{alumno.fecha_nacimiento}}" class="form-control" type="text" name="fecha_nacimiento" disabled>
           </div>
           <br>
           <div class="input-group">
             <span class="input-group-addon"><strong>Docente a Cargo:</strong> </span>
             <input value="{{alumno.docente_encargado}}"type="text" class="form-control" name="docente_encargado" disabled>
           </div>

           <br>
           <div class="input-group">
             <span class="input-group-addon"><strong>Direccion del alumno:</strong> </span>
             <input value="{{alumno.direccion_actual}}" type="text" class="form-control" name="direccion_actual" disabled>
           </div>
           <br>
           <br>
           <div class="input-group">
             <span class="input-group-addon"><strong> Telefono de casa</strong></span>
             <input value="{{alumno.telefono_actual_casa}}" type="text" class="form-control" name="telefono_actual_casa" disabled>
           </div>
           <br>

           <br>
           <div class="input-group">
             <span class="input-group-addon"><strong>Ultimo Centro de estudio:</strong> </span>
             <input value="{{alumno.ultimo_centro_de_estudio}}" type="text" class="form-control" name="ultimo_centro_de_estudio" disabled>
           </div>
           <br>

           </div>

           </form>
           <a href="{% url 'alumnos:listado'%}" class="btn btn-primary "><span class="glyphicon glyphicon-pencil"></span> Volver al listado</a>


</div>

<!-- <script src="{% static 'TableFilter/tablefilter.js'%}"></script> -->


<!-- <script src="{% static 'js/fecha.js'%}"></script> -->
<!--llamando el archivo de fitro DataTables-->

{% endblock %}

aplicaciones/alumnos/templates/eliminar_alumnos.html
{%extends 'index_principal.html' %} {% load staticfiles%} {% block extraheader %} {% endblock %} {% block content %}


<div class="container">
  <div class="row ">
    <div class="col-md-offset-1 col-md-4">
      <div class="eliminar">


        <form method="post">
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
           <strong> Desea eliminiar el alumno:<br>{{alumno.nombre}} {{alumno.apellido}}</strong> <br><br>


          {% csrf_token %}

          <button class="btn btn-danger" type="submit" value="Confirm">Si</button>
          <a class="btn btn-default" href="{% url 'alumnos:listado' %}">Cancelar</a>

        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

aplicaciones/alumnos/templates/index_principal.html
 {%extends 'base/base.html' %}
{% load staticfiles %}
{% block extraheader %}

{% endblock %}

  {% block side_bar %}

<div class="container col-sm-2 ">

  <div class="tabbable tabs-left">

    <ul class="nav nav-tabs">
      <span href="{%url 'alumnos:index_alumnos'%}" class="list-group-item active"><h5>Alumnos</h5></span>
      <li class="nav-tabs"></li>
      <li class="nav-tabs"></li>
      <li><a href="{%url 'alumnos:nuevo'%}" data-toggle="tab">Registrar nuevo</a></li>
      <li><a href="{%url 'alumnos:listado'%}" data-toggle="tab">Listado de Iscritos</a></li>
      <li><a href="#" data-toggle="tab">Cupos por grados</a></li>
      <li><a href="#" data-toggle="tab">Reportes</a></li>
    </ul>
  </div>
</div>


{% endblock side_bar %} {% block content %}
<div class="bs-calltoaction bs-calltoaction-primary">
  <div class="row">
    <div class="col-md-3 cta-contents">
      <img src="{% static "img/mined.png" %}" width="75" height="75" alt="My image"/>

      <h1 class="text-info">Requisitos de Registro:</h1>
      <div class="cta-desc">
        <li class="text-warning">
          Haber cancelado matricula
        </li>
        <li class="text-warning">
          Entregar hoja llena y firmada a docente
        </li>
        <br>
      </div>
    </div>
    <div class="col-md-3 cta-button">
      <a href="#" class="btn btn-lg btn-block btn-primary">Descarga ficha de incripcion</a>
    </div>
  </div>
</div>
{% endblock content %}

aplicaciones/alumnos/templates/listado_alumnos.html
 {%extends 'index_principal.html' %} {% load staticfiles %} {% block extraheader %}

<link rel="stylesheet" href="{% static 'css/datatables.min.css '%}">
{% endblock extraheader %} {% block content %}

<div class="container col-sm-9">
  <div class="row">
    <div class="table-responsive ">{#revisar porque no aparece la barra #}
      <div class="panel panel-primary ">
        <div class="panel-heading">
          <h3 class="panel-title"><i class=""></i><center>Listado de Alumnos Inscritos</center></h3>
        </div>
      </div>
      <table class="table display nowrap table-responsive table-bordered table-hover table-condensed display " table id="Jtabla"  cellspacing="0" width="100  %">
        <thead>
          <tr class="success">
            <th >CODIGO</th>
            <th>NOMBRE</th>
            <th>APELLIDO</th>
            <th>Fecha de Nacimiento</th>
            <th>Docente a cargo</th>
            <th>Ultimo lugar de estudios</th>
            <th>Comentarios del alumno</th>
            {% if perms.alumnos.changue_alumno %}
            <th>Editar </th>
              {% endif %}
            <th>Borrar </th>
            <th>Detalles</th>


          </tr>
        </thead>
        <tbody>
          <tr>
            {% if object_list %} {% for alumno in object_list%}
            <td> {{alumno.id}}</td>
            <td> {{alumno.nombre}}</td>
            <td> {{alumno.apellido}}</td>
            <td> {{alumno.fecha_nacimiento}}</td>
            <td> {{alumno.docente_encargado}}</td>
            <td>{{alumno.ultimo_centro_de_estudio}}</td>
            <td>{{alumno.comentarios}}</td>
            {% if perms.alumnos.changue_alumno %}
            <td>
              <a href="{% url 'alumnos:editar' alumno.id %}" class="btn btn-primary "><span class="glyphicon glyphicon-pencil"></span> Editar</a>
            </td>
            {% endif %}
            <td>
              <a href="{% url 'alumnos:borrar' alumno.id %}" class="btn btn-danger btn-destroy "><span class="glyphicon glyphicon-pencil"></span> Borrar</a>
            </td>
            <td>
              <a href="{% url 'alumnos:detalles' alumno.id %}" class="btn btn-info "><span class="glyphicon glyphicon-pencil"></span> Detalles</a>
            </td>
          </tr>

          {%endfor%} {%else%}
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <h3><strong>No hay registros de alumnos</strong></h3>
          </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- <script src="{% static 'TableFilter/tablefilter.js'%}"></script> -->
<script src="{% static 'js/filtro_Jtabla_Id.js'%}"></script>

<!-- <script src="{% static 'js/fecha.js'%}"></script> -->
<!--llamando el archivo de fitro DataTables-->

{% endblock %}