aplicaciones/usuarios/urls.py
#Urls de la aplicacion docente
from django.conf.urls import url,include
from django.contrib.auth.decorators import login_required
from aplicaciones.usuarios.views import index_usuarios,Registro_usuario,EncargadoListView
urlpatterns = [
    url(r'^index$', login_required(index_usuarios) , name='index_usuarios'),
    url(r'^nuevo$', login_required(Registro_usuario.as_view()) , name='nuevo'),
    url(r'^listado$', login_required(EncargadoListView.as_view()) , name='listado'),




]

registro_inscripcion/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from registro_inscripcion.views import GeneratePdf
from django.contrib.auth.views import login,logout_then_login, password_reset,password_reset_done,password_reset_confirm,password_reset_complete


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^alumnos/', include('aplicaciones.alumnos.urls',namespace="alumnos")),#vista principal de la aplicacion alumnos
    url(r'^docentes/', include('aplicaciones.docentes.urls',namespace="docentes")),#vista principal de la aplicacion alumnos
    # el namespace lo utilizaremos en las templates para llamar una url de manera mas convencional
    url(r'^encargados/', include('aplicaciones.encargados.urls',namespace="encargados")),
    url(r'^usuarios/', include('aplicaciones.usuarios.urls',namespace="usuarios")),
    url(r'^accounts/login/',login,{'template_name':'login.html'}, name='login'),
    url(r'^logout/',logout_then_login,name='logout'),#vista para deslogear usuario
    url(r'^reset/password_reset',password_reset,{'template_name':'password_reset_form.html','email_template_name':'password_reset_email.html'},name='password_reset'),
    url(r'^reset/password_reset_done',password_reset_done,{'template_name':'password_reset_done.html'},name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',password_reset_confirm,{'template_name':'password_reset_confirm.html'},name='password_reset_confirm'),
    url(r'^reset/done',password_reset_complete,{'template_name':'password_reset_complete.html'},name='password_reset_complete'),
    url(r'^pdf/',GeneratePdf.as_view()),
]

aplicaciones/usuarios/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

aplicaciones/usuarios/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth.models import User# usando modelo user que trae django
from django.contrib.auth.forms import UserCreationForm#usuando form que trae django, ya no es
#necesario crear forms.py a menos que se quiera agregar campos como nombre apellido, etc\
from django.views.generic import CreateView,ListView#vista generica basada en clases
from django.core.urlresolvers import reverse_lazy#modulo de volver a una url
from aplicaciones.usuarios.form import Registro_form

# Create your views here.
def index_usuarios(request):
    return render(request,'index_principal_usuarios.html')

class Registro_usuario (CreateView):
    model = User
    template_name = 'CRUD_usuarios.html'
    form_class = Registro_form
    success_url = reverse_lazy('usuarios:index_usuarios')

class EncargadoListView(ListView):

    model = User
    template_name = 'listado_usuarios.html'

aplicaciones/usuarios/templates/CRUD_usuarios.html
{%extends 'index_principal_usuarios.html' %}
{% load staticfiles %}

  {% block extraheader %}
  {% endblock %}
  {% block content %}

<div class="container">



  <div class="row">
    <div class="col-md-offset-1 col-md-5">
      <div class="panel panel-primary ">
        <div class="panel-heading">
          <h3 class="panel-title"><i class=""></i><center>Registre aqui los  Usuarios</center></h3>
        </div>
      </div>
      <div class="formularios">
        <br>
      <form method="post">

        {% csrf_token %}
        <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
        <input id="username" type="text" class="form-control" name="username" placeholder="Nombre de usuario">
      </div>
      <br>
      <div class="input-group">
        <span class="input-group-addon">Nombre:</span>
          <input id="first_name" type="text" class="form-control" name="first_name" placeholder="Nombre">
    </div>
    <br>
        <div class="input-group">
          <span class="input-group-addon">Apellido:</span>
          <input id="last_name" type="text" class="form-control" name="last_name" placeholder="Apellido">
      </div>
      <br>

          <div class="input-group">
            <span class="input-group-addon">@ejemplo.com</span>
            <input type="text" class="form-control" id="email" name="email"placeholder="Ingrese un Email valido">

        </div>
        <br>
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
            <input id="password1" name="password1" type="password" class="form-control" name="password" placeholder="Ingrese su Contraseña">
          </div>
          <br>
          <div class="input-group">
              <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
              <input id="password2" name="password2" type="password" class="form-control" name="password" placeholder="Confirme su Contraseña">
            </div>
            <br>
            <div class="alert alert-success"><p>Si todos los datos son correctos click en: <button type="submit" class="btn btn-success">GUARDAR</button></p>
            </div>


      </form>
  </div>
    </div>
  </div>

  {% endblock %}

aplicaciones/usuarios/templates/index_principal_usuarios.html
 {%extends 'base/base.html' %}
 {% load staticfiles %}
 {% block side_bar %}

<div class="container col-md-2 ">

  <div class="tabbable tabs-left ">

    <ul class="nav nav-tabs">

        <a href="{%url 'usuarios:index_usuarios'%}"class="list-group-item active"><h5> Usuarios</h5></a>
      <li class="nav-tabs"></li>
      <li><a href="{% url 'usuarios:nuevo' %}" data-toggle="tab">Crear Usuario</a></li>
      <li><a href="{% url 'usuarios:listado' %}" data-toggle="tab">Ver listado de usuarios</a></li>
      <li><a href="">Permisos de usuarios</a></li>
      <li><a href="" data-toggle="tab">Reportes</a></li>
    </ul>
  </div>

</div>

{% endblock side_bar %} {% block content %}
<div class="bs-calltoaction bs-calltoaction-primary">
  <div class="row">
    <div class="col-md-8 cta-contents">
      <img src="{% static "img/mined.png" %}" width="75" height="75" alt="My image"/>

      <h1 class="text-info">Registro de Usuarios</h1>
      <div class="cta-desc">
        <li class="text-warning">
          Que es un nombre de usuario
        </li>
        <li class="text-warning">
          Quienes que persimos debe tener un usuario
        </li>
        <li class="text-warning">
          Quien puede borrar un usuario
        </li>
        <br>
      </div>
    </div>

  </div>
</div>
  {% endblock content %}

aplicaciones/usuarios/templates/listado_usuarios.html
{%extends 'index_principal_usuarios.html' %}
 {% load staticfiles %}
 {% block extraheader %}
<link rel="stylesheet" href="{% static 'css/datatables.min.css '%}"> {% endblock extraheader %} {% block content %}
<div class="container-fluid col-sm-9">
  <div class="row-fluid">
    <div class="table-responsive">
      <div class="panel panel-primary ">
        <div class="panel-heading">
          <h3 class="panel-title"><i class=""></i><center>Listado de Usuarios</center></h3>
        </div>
      </div>
      <table class="table  table-bordered table-hover table-condensed table-responsive" table id="Jtabla" class="display" cellspacing="0" width="100%">
        <thead>
          <tr class="success">
            <th>Nombre de usuarios</th>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Email de recuperacion</th>
            <th>Fecha de Ingreso al sistema</th>

          </tr>
        </thead>
        <tbody>
          <tr>
            {% if object_list%} {% for usuario in object_list%}
            <td> {{usuario.username}}</td>
            <td> {{usuario.first_name}}</td>
            <td>{{usuario.last_name}}</td>
            <td>{{usuario.email}}</td>
            <td>{{usuario.last_login}}</td>

                      </tr>
          {%endfor%} {%else%}
          <h1>No hay ningun Docente Registrado</h1> {%endif%}
        </tbody>
      </table>
    </div>
  </div>
</div>
<script src="{% static 'js/filtro_Jtabla_Id.js'%}"></script>

{% endblock %}