aplicaciones/docentes/urls.py
#Urls de la aplicacion docente
from django.conf.urls import url,include
from django.contrib.auth.decorators import login_required
from aplicaciones.docentes.views import index_docentes,index_secciones,DocenteCreateView,\
DocenteListView,DocenteUpdateView,DocenteDeleteView,SeccionesCreateView,SeccionesListView

urlpatterns = [
    url(r'^index$', login_required(index_docentes) , name='index_docentes'),# el signo $ indica que es una exprecion regular, cadena vacia junto con el signo ^.
    url(r'^nuevo$', login_required(DocenteCreateView.as_view()), name='nuevo'),
    url(r'^listado$', login_required(DocenteListView.as_view()), name='listado'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(DocenteUpdateView.as_view()), name='editar'),
    url(r'^borrar/(?P<pk>\d+)/$', login_required(DocenteDeleteView.as_view()), name='borrar'),
    ###### URLS DE LAS SECCIONES ######
    url(r'^index_secciones$',login_required(index_secciones) , name='index_secciones'),
    url(r'^nuevas_secciones$', login_required(SeccionesCreateView.as_view()), name='nuevas_secciones'),
    url(r'^listados_secciones$', login_required(SeccionesListView.as_view()), name='listados_secciones'),


]

registro_inscripcion/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from registro_inscripcion.views import GeneratePdf
from django.contrib.auth.views import login,logout_then_login, password_reset,password_reset_done,password_reset_confirm,password_reset_complete


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^alumnos/', include('aplicaciones.alumnos.urls',namespace="alumnos")),#vista principal de la aplicacion alumnos
    url(r'^docentes/', include('aplicaciones.docentes.urls',namespace="docentes")),#vista principal de la aplicacion alumnos
    # el namespace lo utilizaremos en las templates para llamar una url de manera mas convencional
    url(r'^encargados/', include('aplicaciones.encargados.urls',namespace="encargados")),
    url(r'^usuarios/', include('aplicaciones.usuarios.urls',namespace="usuarios")),
    url(r'^accounts/login/',login,{'template_name':'login.html'}, name='login'),
    url(r'^logout/',logout_then_login,name='logout'),#vista para deslogear usuario
    url(r'^reset/password_reset',password_reset,{'template_name':'password_reset_form.html','email_template_name':'password_reset_email.html'},name='password_reset'),
    url(r'^reset/password_reset_done',password_reset_done,{'template_name':'password_reset_done.html'},name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',password_reset_confirm,{'template_name':'password_reset_confirm.html'},name='password_reset_confirm'),
    url(r'^reset/done',password_reset_complete,{'template_name':'password_reset_complete.html'},name='password_reset_complete'),
    url(r'^pdf/',GeneratePdf.as_view()),
]

aplicaciones/docentes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models



class Secciones(models.Model):

    opciones_turnos = (
        ('0', ''),
        ('MATUTINO', 'MATUTITO'),
        ('TARDE', 'TARDE'),
        ('FIN DE SEMANA', 'FIN DE SEMANA')

    )
    #crear campo de a;o de estudio usar un count
    turno = models.CharField(max_length=40, choices=opciones_turnos,default='MATUTITO')
    nombre_seccion= models.CharField(blank=False,max_length=30)
    cupor_por_seccion = models.IntegerField(blank=True, null=True)

    def __unicode__(self):#funcion para que se nos devuelva el nombre y no el objeto
	#que hemos registrado
		return '{}'.format(self.nombre_seccion)

# Create your models here.
class Docente(models.Model):
    #campos de el modelo del docente o atributos que comtendra la tabla
    # de los docentes
    dui_docente =  models.CharField(blank=False, max_length=30,default='')
    nombre = models.CharField(blank=False, max_length=30)
    apellido = models.CharField(blank=False, max_length=30)
    nip_docente=models.CharField(blank=False, max_length=20,null=True)
    seccion_cargo = models.ForeignKey(Secciones,null= True, blank= True,max_length=15)
    #corregir este campo mas tarde


    #revisa si el docente puede tener mas de una seccion a cargo
    def __unicode__(self):#funcion para que se nos devuelva el nombre y no el objeto
	#que hemos registrado
		return '{}'.format(self.nombre)

aplicaciones/docentes/forms.py
from django import forms
from aplicaciones.docentes.models import Docente,Secciones# importando modelo alumno


class Docente_Form(forms.ModelForm):
    class Meta:
        model=Docente

        fields = [
            'nombre',
            'apellido',
            'seccion_cargo',
            'dui_docente',
            'nip_docente',

        ]
        labels = {
            'nombre'  :'Nombre',
            'apellido' :'Apellido',
            'seccion_cargo' :'GRADO',
            'dui_docente':'Numero de dui',
            'nip_docente':'Numero de identificacion',

        }
        widgets = {
            'nombre' : forms.TextInput(attrs={'class':'form-control'}),
            'apellido':forms.TextInput(attrs={'class':'form-control'}),
            'seccion_cargo':forms.Select(attrs={'class':'form-control'}),
            'dui_docente':forms.TextInput(attrs={'class':'form-control'}),
            'nip_docente':forms.TextInput(attrs={'class':'form-control'}),

        }


class Secciones_Form(forms.ModelForm):
    class Meta:
        model=Secciones

        fields = [
            'turno',
            'nombre_seccion',
            'cupor_por_seccion',




        ]
        labels = {
            'turno'  :'Turno',
            'nombre_seccion' :'Nombre de la Seccion',
            'cupor_por_seccion' :'Cupo de esta seccion',


        }
        widgets = {
            'turno' : forms.Select(attrs={'class':'form-control'}),
            'nombre_seccion':forms.TextInput(attrs={'class':'form-control'}),
            'cupor_por_seccion':forms.TextInput(attrs={'class':'form-control'}),

        }

aplicaciones/docentes/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from aplicaciones.docentes.forms import Docente_Form,Secciones_Form
from aplicaciones.docentes.models import Docente,Secciones

#vista principal docentes
def index_docentes(request):
    return render(request,'index_principal_docentes.html')



class DocenteListView(ListView):
    model = Docente
    template_name = 'listado_docentes.html'

#vista para crear docentes
#
class DocenteCreateView(CreateView):
    model = Docente
    #indocamos el modelo que en que se basa esta vista con la propiedad model
    form_class = Docente_Form
    #le pasamos el formulario creado a la propiedad form_class
    template_name = 'CRUD_docentes.html'
    #colocamos el formulario que va a usar esta vista con el atributo template_name
    success_url = reverse_lazy('docentes:index_docentes')
    #con success_url redirigimos luego de guardar nuestros registros
    #
    #
class DocenteUpdateView(UpdateView):
    model = Docente#indicando el nombre del modelo a usar
    form_class = Docente_Form#atributo form class se usa
    # para guardar el formulario que hemos creado
    template_name = 'CRUD_docentes.html'#se coloca el templateview
    #que se va a utilizar
    success_url = reverse_lazy('docentes:index_docentes')#indicando la url
    #a la que volvera luego de guardado el objeto
    #
    #
class DocenteDeleteView(DeleteView):
    model = Docente
    template_name = 'eliminar_docentes.html'
    success_url =reverse_lazy('docentes:listado')

###################vistas de las secciones############################

def index_secciones(request):
    return render(request,'index_principal_secciones.html')

class SeccionesListView(ListView):
    model = Secciones
    template_name = 'listado_secciones.html'

class SeccionesCreateView(CreateView):
    model = Secciones
    form_class = Secciones_Form
    template_name = 'CRUD_secciones.html'
    success_url = reverse_lazy('docentes:listados_secciones')

aplicaciones/docentes/templates/CRUD_docentes.html
{%extends 'index_principal_docentes.html' %} {% block content %}

<div class="container">
	<div class="row">
		<div class="col-sm-offset-1 col-md-4">
			<div class="panel panel-primary ">
				<div class="panel-heading">
					<h3 class="panel-title"><i class=""></i><center>Registro de Docentes</center></h3>
				</div>
			</div>
			<div class="formularios">
				<form method="post">

					{% csrf_token %}
					<br>
					<div class="input-group">
						<span class="input-group-addon">Nombre del Docente:</span>
						<input value="{{docente.nombre}}" type="text" class="form-control" name="nombre" placeholder="Nombre de Docente">
					</div>
					<br>
					<br>
					<div class="input-group">
						<span class="input-group-addon">Apellido del Docente:</span>
						<input value="{{docente.apellido}}" type="text" class="form-control" name="apellido" placeholder="Apellido Docente">
					</div>
					<br>
					<div class="input-group">
						<span class="input-group-addon">DUI:</span>
						<input value="{{docente.dui_docente}}" type="text" class="form-control" name="dui_docente" placeholder="Numero de Dui sin guiones">
						<br>
					</div>
					<br>
					<div class="input-group">
						<span class="input-group-addon">NIP:</span>
						<input value="{{docente.nip_docente}}" type="text" class="form-control" name="nip_docente" placeholder="Numero de identificacion docente">
						<br>
					</div>
					<br>
					<div class="input-group">
	          <span class="input-group-addon">Seccion a cargo</span>
	          <option value="{{docente.id}}">{{form.seccion_cargo}} </option>
	        </div>
					<br>
					<button type="submit">Guardar</button>

				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

aplicaciones/docentes/templates/CRUD_secciones.html
{%extends 'index_principal_secciones.html' %} {% block content %}

<div class="container">
	<div class="row">
		<div class="col-sm-offset-1 col-md-5">
			<div class="panel panel-primary ">
				<div class="panel-heading">
					<h3 class="panel-title"><i class=""></i><center>Crear Secciones</center></h3>
				</div>
			</div>
			<form method="post">

				{% csrf_token %}
				<div class="input-group">
					<div class="form-group">
						<label for="sel1">Select list:</label>
						<select class="form-control" id="" name="turno">
							 <option>MATUTINO</option>
							 <option>TARDE</option>
							 <option>FIN DE SEMANA</option>

 					 	</select>
					</div>

				</div>
				<br>
				<div class="input-group">
					<span class="input-group-addon">Nombre</span>
					<input type="text" name="nombre_seccion" class="form-control" placeholder="Nombre de la seccion">

				</div>
				<br>
				<div class="input-group">
					<span class="input-group-addon">Cupos </span>
					<input type="text" name="cupor_por_seccion" class="form-control" placeholder="Asignar numero de cupo">

				</div>
				<br>
				<button type="submit">Guardar</button>

			</form>
		</div>
	</div>
</div>
{% endblock %}

aplicaciones/docentes/templates/eliminar_docentes.html
{%extends 'index_principal.html' %} {% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-offset-1 col-md-5">
                <form method="post">

                    {% csrf_token %}
                    <h3><strong>¿Desea borrar el Docente :{{docente.nombre}} {{docente.apellido}}?</strong> </h3>

                    <button class="btn btn-danger btn-destroy" type="submit">Borrar</button>
                    <a href="{%url 'docentes:listado'%}" class="btn btn-primary a-btn-slide-text">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    <span>Cancelar</span>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

aplicaciones/docentes/templates/index_principal_docentes.html
 {%extends 'base/base.html' %}
{% load staticfiles %}
  {% block side_bar %}

<div class="container col-md-2 ">

  <div class="tabbable tabs-left">

    <ul class="nav nav-tabs">
    <a href="{%url 'docentes:index_docentes'%}" data-toggle="tab"class="list-group-item active"><h5>docentes</h5></a>
      <li class="nav-tabs"></li>
      <li class="nav-tabs"></li>
      <li><a href="{%url 'docentes:nuevo'%}" data-toggle="tab">Nuevo</a></li>
      <li><a href="{%url 'docentes:listado'%}" data-toggle="tab">Lista de Maestros</a></li>
      <li><a href="#" data-toggle="tab">Ver por grados a cargo</a></li>
      <li><a href="#" data-toggle="tab">Reportes</a></li>
    </ul>
  </div>

</div>

{% endblock side_bar %} {% block content %}
<div class="bs-calltoaction bs-calltoaction-primary">
  <div class="row">
    <div class="col-md-8 cta-contents">
      <img src="{% static "img/mined.png" %}" width="75" height="75" alt="My image"/>

      <h1 class="text-info">Datos de Docentes:</h1>
      <div class="cta-desc">
        <li class="text-warning">
          DUI
        </li>
        <li class="text-warning">
          NIT
        </li>
        <li class="text-warning">
          TELEFONO
        </li>
        <br>
      </div>
    </div>
    <div class="col-md-3 cta-button">
      <a href="#" class="btn btn-lg btn-block btn-primary">Descarga formulario de docentes</a>
    </div>
  </div>
</div>
  {% endblock content %}

aplicaciones/docentes/templates/index_principal_secciones.html
 {%extends 'base/base.html' %}
 {% load staticfiles %}
 {% block side_bar %}

<div class="container col-md-2 ">

  <div class="tabbable tabs-left">

    <ul class="nav nav-tabs">
    <a href="" data-toggle="tab"class="list-group-item active"><h5>Secciones</h5></a>
      <li class="nav-tabs"></li>
      <li class="nav-tabs"></li>
      <li><a href="{% url 'docentes:nuevas_secciones'%}" data-toggle="tab">Crear seccion</a></li>
      <li><a href="{% url 'docentes:listados_secciones'%}" data-toggle="tab">Listado de secciones</a></li>
      <li><a href="" data-toggle="tab">Cupos limite por seccion</a></li>
      <li><a href="" data-toggle="tab">Reportes</a></li>
    </ul>
  </div>

</div>

{% endblock side_bar %} {% block content %}
<div class="bs-calltoaction bs-calltoaction-primary">
  <div class="row">
    <div class="col-md-8 cta-contents">
      <img src="{% static "img/mined.png" %}" width="75" height="75" alt="My image"/>

      <h1 class="text-info">Secciones de nuestro centro educativo</h1>
      <div class="cta-desc">
        <li class="text-warning">
          Clasificacion
        </li>
        <li class="text-warning">
          Edades permitidas
        </li>
        <li class="text-warning">
          Datos importantes
        </li>
        <br>
      </div>
    </div>

  </div>
</div>
  {% endblock content %}

aplicaciones/docentes/templates/listado_docentes.html
{%extends 'index_principal_docentes.html' %} {% load staticfiles %} {% block extraheader %}
<link rel="stylesheet" href="{% static 'css/datatables.min.css '%}"> {% endblock extraheader %} {% block content %}
<div class="container-fluid col-sm-9">
  <div class="row-fluid">
    <div class="table-responsive">
      <div class="panel panel-primary ">
        <div class="panel-heading">
          <h3 class="panel-title"><i class=""></i><center>Listado de Docentes</center></h3>
        </div>
      </div>
      <table class="table  table-bordered table-hover table-condensed table-responsive" table id="Jtabla" class="display" cellspacing="0" width="100%">
        <thead>
          <tr class="success">
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Grado a cargo</th>
            <th>DUI DEL DOCENTE</th>
            <th>Opciones</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            {% if object_list%} {% for docente in object_list%}
            <td> {{docente.nombre}}</td>
            <td> {{docente.apellido}}</td>
            {% if docente.seccion_cargo%}
            <td>{{docente.seccion_cargo}}</td>
            {% else %}
            <td></td>
            {%endif%}
            <td>{{docente.dui_docente}}</td>
            <td>
              <a href="{% url 'docentes:editar' docente.id %}" class="btn btn-primary "><span class="glyphicon glyphicon-pencil"></span> Editar</a>
              <a href="{% url 'docentes:borrar' docente.id %}" class="btn btn-danger btn-destroy "><span class="glyphicon glyphicon-pencil"></span> Borrar</a>
            </td>
          </tr>
          {%endfor%} {%else%}
          <h1>No hay ningun Docente Registrado</h1> {%endif%}
        </tbody>
      </table>
    </div>
  </div>
</div>
<script src="{% static 'js/filtro_Jtabla_Id.js'%}"></script>

{% endblock %}

aplicaciones/docentes/templates/listado_secciones.html
{%extends 'index_principal_secciones.html' %}
{% load staticfiles %}
{% block extraheader %}
<link rel="stylesheet" href="{% static 'css/datatables.min.css '%}"> {% endblock extraheader %} {% block content %}
<div class="container-fluid col-sm-9">
  <div class="row-fluid">
    <div class="table-responsive">
      <div class="panel panel-primary ">
        <div class="panel-heading">
          <h3 class="panel-title"><i class=""></i><center>Listado de Docentes</center></h3>
        </div>
      </div>
      <table class="table  table-bordered table-hover table-condensed table-responsive" table id="Jtabla" class="display" cellspacing="0" width="100%">
        <thead>
          <tr class="success">
            <th>Seccion</th>
            <th>Turno</th>
            <th>Cupos asignados</th>

          </tr>
        </thead>
        <tbody>
          <tr>
            {% if object_list%} {% for seccion in object_list%}
            <td> {{seccion.nombre_seccion}}</td>
            <td> {{seccion.turno}}</td>
            <td>{{seccion.cupor_por_seccion}}</td>

          </tr>
          {%endfor%} {%else%}
          <h1>No hay ningun Docente Registrado</h1>
          {%endif%}
        </tbody>
      </table>
    </div>
  </div>
</div>
<script src="{% static 'js/filtro_Jtabla_Id.js'%}"></script>

{% endblock %}